[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snake_synthesizers"
version = "0.0.1"
requires-python = ">=3.7"

[tool.hatch.build.targets.wheel]
packages = ["snake_synthesizers"]